env:
  global:
#    secure: "Mc+HCf8MmK28kZwaZ7YZox9qAlCP81pLLQVQMCH9yxCwFBUJlxO0+jsimoMhe6K9hi0WE1pS6Qa6+v0GdZ0+FmIlX1sQh5X64NCjCZHY3lcnFoPI8FSspgp0jRNd0Y1DPBWeLsuM2kmw9oaeQ8kqR7RYXLvkEHYfqbip1RkPRzfTJnB9OCdxWGfPrahD5idRyx2dfhw176vGF8h5aeTaajNvLhBGae2OerbEO0S4tf0jGUTVOJSPCJo2tcaCFIUcS+4fgNkqace4vtY7ZgJUstPpG6Ajj5lHFhfjEQrXlsn5Wv5eflvrO8XkXPGGC9Ttbqx/+zOwPxbjlneDEP6QyEfduxOzvLWM6TV8spNbI9z+X+dkRMovl5zgZrY9PzsM/cBcg3GS3rMUVrCHuJWNxcsX6oihKg4Dso8LZrvQXpmG4Ucgq4vbF+pzRI2frzuwW4SoddiKfz2cGrihkso0+nnuWe1a7NzjJzVR1oq6yA5GV4WWFIJT56OJ8Ta4y4dAKbgIhg7YFHfahfvc62B5BElxa9TtBIkud1sLDN2l6VEhso2sFpywQxbNXfLTV7GA4NIGAUPLf4qzBNE1kNkjaX6sdfY6MvzCyfWmui+KgZxRSZeUJ2bboP/0l0vuuDzLUlUUeqom8aGJfuQbXnGhld1vzqtvmc2DSLIEJ1v8V6c="
notifications:
  email: false
git:
  quiet: true
  depth: false
language: node_js
node_js: lts/*
services:
  - xvfb
python: 3.7
addons:
  apt:
    update: false
    packages:
      - curl
      - python3-pip
#      - libappindicator1
#      - fonts-liberation
#      - google-chrome-stable
install: true
before_install:
#  - |
#    export CHROME_BIN=/usr/bin/google-chrome
#    export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash
    stop_any 3000 5000
  - |
    export PATH=$HOME/.local/bin:$PATH
    pip3 install --user --upgrade pip setuptools
    pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      name: stylus-flex
      before_script:
        - cd $TRAVIS_BUILD_DIR/stylus-flex && npm i -E
        - cd $TRAVIS_BUILD_DIR/stylus-flex && npm run serve &
        - stop_any 5000
      script:
        - http :5000
      after_script:
        - stop_any 5000
#  - stage: deploy
#    jdk: openjdk11
#    name: GitHub Pages
#    script: skip
#    before_deploy:
#    - set -e
#    - mkdir -p ${HOME}/.m2
#    - ./mvnw -pl :from-zero-to-reactive-cloud-micro-hero -P npm-run-gh-pages
#    deploy: &pages
#      provider: pages
#      skip-cleanup: true
#      github-token: "$GITHUB_TOKEN"
#      keep-history: true
#      local-dir: docs/.vuepress/dist
#      target_branch: gh-pages
#      on:
#        branch: master
#        condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  npm: true
  pip: true
  packages: true
  directories:
  - ~/.n*
  - ~/.local/daggerok
